const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
    CUSTOMER_LOGIN_FAIL: 'CUSTOMER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    CUSTOMER_REGISTER_SUCCESS: 'CUSTOMER_REGISTER_SUCCESS',
    CUSTOMER_REGISTER_FAIL: 'CUSTOMER_REGISTER_FAIL',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_TOP_STAFFS_SUCCESS: 'FETCH_TOP_STAFFS_SUCCESS',
    FETCH_TOP_STAFFS_FAILED: 'FETCH_TOP_STAFFS_FAILED',

    FETCH_ALL_STAFFS_SUCCESS: 'FETCH_ALL_STAFFS_SUCCESS',
    FETCH_ALL_STAFFS_FAILED: 'FETCH_ALL_STAFFS_FAILED',

    SAVE_DETAIL_STAFF_SUCCESS: 'SAVE_DETAIL_STAFF_SUCCESS',
    SAVE_DETAIL_STAFF_FAILED: 'SAVE_DETAIL_STAFF_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    FETCH_REQUIRED_STAFF_INFOR_START: 'FETCH_REQUIRED_STAFF_INFOR_START',
    FETCH_REQUIRED_STAFF_INFOR_SUCCESS: 'FETCH_REQUIRED_STAFF_INFOR_SUCCESS',
    FETCH_REQUIRED_STAFF_INFOR_FAILED: 'FETCH_REQUIRED_STAFF_INFOR_FAILED',

    FETCH_ALL_NEWS_SUCCESS: 'FETCH_ALL_NEWS_SUCCESS',
    FETCH_ALL_NEWS_FAILED: 'FETCH_ALL_NEWS_FAILED',

    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_FAILED: 'DELETE_NEWS_FAILED',

    EDIT_NEWS_SUCCESS: 'EDIT_NEWS_SUCCESS',
    EDIT_NEWS_FAILED: 'EDIT_NEWS_FAILED',

    FETCH_ALL_SERVICE_SUCCESS: 'FETCH_ALL_SERVICE_SUCCESS',
    FETCH_ALL_SERVICE_FAILED: 'FETCH_ALL_SERVICE_FAILED',

    FETCH_TOP_SERVICES_SUCCESS: 'FETCH_TOP_SERVICES_SUCCESS',
    FETCH_TOP_SERVICES_FAILED: 'FETCH_TOP_SERVICES_FAILED',

    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAILED: 'CREATE_SERVICE_FAILED',

    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_FAILED: 'DELETE_SERVICE_FAILED',

    EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE_SUCCESS',
    EDIT_SERVICE_FAILED: 'EDIT_SERVICE_FAILED',

    FETCH_ALL_SHOWROOM_SUCCESS: 'FETCH_ALL_SHOWROOM_SUCCESS',
    FETCH_ALL_SHOWROOM_FAILED: 'FETCH_ALL_SHOWROOM_FAILED',

    DELETE_SHOWROOM_SUCCESS: 'DELETE_SHOWROOM_SUCCESS',
    DELETE_SHOWROOM_FAILED: 'DELETE_SHOWROOM_FAILED',

    EDIT_SHOWROOM_SUCCESS: 'EDIT_SHOWROOM_SUCCESS',
    EDIT_SHOWROOM_FAILED: 'EDIT_SHOWROOM_FAILED',

    FETCH_ALL_BOOKING_SUCCESS: 'FETCH_ALL_BOOKING_SUCCESS',
    FETCH_ALL_BOOKING_FAILED: 'FETCH_ALL_BOOKING_FAILED',

    DELETE_BOOKING_SUCCESS: 'DELETE_BOOKING_SUCCESS',
    DELETE_BOOKING_FAILED: 'DELETE_BOOKING_FAILED',

    FETCH_CUSTOMER_BOOKING_SUCCESS: 'FETCH_CUSTOMER_BOOKING_SUCCESS',
    FETCH_CUSTOMER_BOOKING_FAILED: 'FETCH_CUSTOMER_BOOKING_FAILED',

    // customer
    FETCH_CAR_START: 'FETCH_CAR_START',
    FETCH_CAR_SUCCESS: 'FETCH_CAR_SUCCESS',
    FETCH_CAR_FAILED: 'FETCH_CAR_FAILED',
})

export default actionTypes;

